-- Seed metadata for the design reference library (images added later).
-- Mirrors the catalog in design/references/README.md.

INSERT INTO public.design_elements (category, name, source_board, sort_order) VALUES
  ('text-animations','fade_up','text-animations',1),
  ('text-animations','slide_from_left','text-animations',2),
  ('text-animations','character_stagger','text-animations',3),
  ('text-animations','word_reveal','text-animations',4),
  ('text-animations','scale_pop','text-animations',5),
  ('text-animations','rotate_in','text-animations',6),
  ('text-animations','glitch_reveal','text-animations',7),
  ('text-animations','wave_animation','text-animations',8),
  ('text-animations','type_writer','text-animations',9),
  ('text-animations','split_reveal','text-animations',10),
  ('text-animations','blur_to_focus','text-animations',11),
  ('text-animations','gradient_sweep','text-animations',12),

  ('scroll-animations','fade_up','scroll-animations',1),
  ('scroll-animations','stagger_appear','scroll-animations',2),
  ('scroll-animations','parallax_layers','scroll-animations',3),
  ('scroll-animations','rotate_in','scroll-animations',4),
  ('scroll-animations','scale_reveal','scroll-animations',5),
  ('scroll-animations','slide_from_sides','scroll-animations',6),
  ('scroll-animations','morph_shapes','scroll-animations',7),
  ('scroll-animations','progress_indicators','scroll-animations',8),
  ('scroll-animations','number_counter','scroll-animations',9),
  ('scroll-animations','text_reveal','scroll-animations',10),
  ('scroll-animations','image_zoom','scroll-animations',11),
  ('scroll-animations','timeline_animation','scroll-animations',12),

  ('page-transitions','slide_from_right','page-transitions',1),
  ('page-transitions','fade_with_scale','page-transitions',2),
  ('page-transitions','curtain_reveal','page-transitions',3),
  ('page-transitions','rotation_flip','page-transitions',4),
  ('page-transitions','liquid_morph','page-transitions',5),
  ('page-transitions','glitch_effect','page-transitions',6),
  ('page-transitions','particle_dissolve','page-transitions',7),
  ('page-transitions','zoom_blur','page-transitions',8),
  ('page-transitions','wipe_with_glow','page-transitions',9),
  ('page-transitions','cube_transition','page-transitions',10),
  ('page-transitions','ripple_effect','page-transitions',11),
  ('page-transitions','shutter_split','page-transitions',12),

  ('card-layouts','standard_grid','card-layouts',1),
  ('card-layouts','masonry','card-layouts',2),
  ('card-layouts','featured_grid','card-layouts',3),
  ('card-layouts','horizontal_scroll','card-layouts',4),
  ('card-layouts','staggered_grid','card-layouts',5),
  ('card-layouts','asymmetric','card-layouts',6),
  ('card-layouts','carousel_cards','card-layouts',7),
  ('card-layouts','stacked_cards','card-layouts',8),
  ('card-layouts','timeline_cards','card-layouts',9),
  ('card-layouts','two_column_mix','card-layouts',10),
  ('card-layouts','grid_with_sidebar','card-layouts',11),
  ('card-layouts','infinite_scroll','card-layouts',12),

  ('card-hover','lift_with_shadow','card-hover',1),
  ('card-hover','tilt_3d','card-hover',2),
  ('card-hover','expand_borders','card-hover',3),
  ('card-hover','particle_burst','card-hover',4),
  ('card-hover','glow_pulse','card-hover',5),
  ('card-hover','frosted_glass_spread','card-hover',6),
  ('card-hover','flip_card','card-hover',7),
  ('card-hover','scale_with_blur','card-hover',8),
  ('card-hover','shine_effect','card-hover',9),
  ('card-hover','magnetic_pull','card-hover',10),
  ('card-hover','liquid_spread','card-hover',11),
  ('card-hover','neon_border','card-hover',12),
  ('card-hover','glass_crack','card-hover',13),
  ('card-hover','hologram_glitch','card-hover',14),
  ('card-hover','rotation_orbit','card-hover',15),
  ('card-hover','gradient_shift','card-hover',16),
  ('card-hover','neon_outline_pulse','card-hover',17),

  ('card-hover-themes','crimson_lift','card-hover-themes',1),
  ('card-hover-themes','emerald_tilt','card-hover-themes',2),
  ('card-hover-themes','ocean_float','card-hover-themes',3),
  ('card-hover-themes','galaxy_expand','card-hover-themes',4),
  ('card-hover-themes','sunset_glow','card-hover-themes',5),
  ('card-hover-themes','ice_frost','card-hover-themes',6),
  ('card-hover-themes','matrix_scan','card-hover-themes',7),
  ('card-hover-themes','neon_pulse','card-hover-themes',8),
  ('card-hover-themes','magnetic_attract','card-hover-themes',9),
  ('card-hover-themes','particle_trail','card-hover-themes',10),

  ('card-bg-textures','neon_laser_grid','card-bg-textures',1),
  ('card-bg-textures','quantum_particle_field','card-bg-textures',2),
  ('card-bg-textures','metallic_accordion','card-bg-textures',3),
  ('card-bg-textures','holographic_data_stream','card-bg-textures',4),
  ('card-bg-textures','crystalline_ice','card-bg-textures',5),
  ('card-bg-textures','flowing_lava_plasma','card-bg-textures',6),
  ('card-bg-textures','geometric_mandala','card-bg-textures',7),
  ('card-bg-textures','glitch_hologram','card-bg-textures',8),

  ('hero-backgrounds','hero_space_bg','hero-backgrounds',1),
  ('hero-backgrounds','wave_background','hero-backgrounds',2),
  ('hero-backgrounds','grid_perspective','hero-backgrounds',3),
  ('hero-backgrounds','aurora_hero','hero-backgrounds',4),
  ('hero-backgrounds','constellation_bg','hero-backgrounds',5),
  ('hero-backgrounds','floating_shapes','hero-backgrounds',6),
  ('hero-backgrounds','mesh_gradient','hero-backgrounds',7),
  ('hero-backgrounds','tunnel_grid','hero-backgrounds',8),
  ('hero-backgrounds','neon_tunnel','hero-backgrounds',9),
  ('hero-backgrounds','network_constellation','hero-backgrounds',10),
  ('hero-backgrounds','volcano_sunset','hero-backgrounds',11),
  ('hero-backgrounds','matrix_grid','hero-backgrounds',12),
  ('hero-backgrounds','purple_galaxy','hero-backgrounds',13),
  ('hero-backgrounds','aurora_ice','hero-backgrounds',14),
  ('hero-backgrounds','lightning','hero-backgrounds',15),
  ('hero-backgrounds','teal_particles','hero-backgrounds',16),

  ('animated-bg-patterns','particle_field','animated-bg-patterns',1),
  ('animated-bg-patterns','grid_lines','animated-bg-patterns',2),
  ('animated-bg-patterns','wave_gradient','animated-bg-patterns',3),
  ('animated-bg-patterns','geometric_shapes','animated-bg-patterns',4),
  ('animated-bg-patterns','dot_matrix','animated-bg-patterns',5),
  ('animated-bg-patterns','mesh_gradient','animated-bg-patterns',6),
  ('animated-bg-patterns','starfield','animated-bg-patterns',7),
  ('animated-bg-patterns','circuit_pattern','animated-bg-patterns',8),
  ('animated-bg-patterns','hexagon_tiles','animated-bg-patterns',9),
  ('animated-bg-patterns','aurora_borealis','animated-bg-patterns',10),
  ('animated-bg-patterns','liquid_metal','animated-bg-patterns',11),
  ('animated-bg-patterns','holographic_grid','animated-bg-patterns',12),

  ('lighting-backgrounds','spotlight','lighting-backgrounds',1),
  ('lighting-backgrounds','glow_orbs','lighting-backgrounds',2),
  ('lighting-backgrounds','light_rays','lighting-backgrounds',3),
  ('lighting-backgrounds','neon_glow','lighting-backgrounds',4),
  ('lighting-backgrounds','lens_flare','lighting-backgrounds',5),
  ('lighting-backgrounds','rim_light','lighting-backgrounds',6),
  ('lighting-backgrounds','ambient_glow','lighting-backgrounds',7),
  ('lighting-backgrounds','point_lights','lighting-backgrounds',8),
  ('lighting-backgrounds','gradient_glow','lighting-backgrounds',9),
  ('lighting-backgrounds','reflection_light','lighting-backgrounds',10),
  ('lighting-backgrounds','caustics','lighting-backgrounds',11),
  ('lighting-backgrounds','aurora_lights','lighting-backgrounds',12),

  ('parallax-layers','far_background','parallax-layers',1),
  ('parallax-layers','mid_background','parallax-layers',2),
  ('parallax-layers','foreground','parallax-layers',3),
  ('parallax-layers','overlay','parallax-layers',4),
  ('parallax-layers','floating_shapes','parallax-layers',5),
  ('parallax-layers','light','parallax-layers',6),
  ('parallax-layers','grid','parallax-layers',7),
  ('parallax-layers','particle','parallax-layers',8),
  ('parallax-layers','blur','parallax-layers',9),
  ('parallax-layers','shadow','parallax-layers',10),
  ('parallax-layers','glow','parallax-layers',11),
  ('parallax-layers','detail','parallax-layers',12),

  ('buttons','primary_cta','buttons',1),
  ('buttons','glass','buttons',2),
  ('buttons','chrome','buttons',3),
  ('buttons','holographic','buttons',4),
  ('buttons','hover_effect','buttons',5),
  ('buttons','pulse_animation','buttons',6),
  ('buttons','raised_3d','buttons',7),
  ('buttons','pill','buttons',8),

  ('navigation','glass_navbar','navigation',1),
  ('navigation','neon_tabs','navigation',2),
  ('navigation','nav_menu_3d','navigation',3),
  ('navigation','holographic_sidebar','navigation',4),
  ('navigation','progress_bar','navigation',5),
  ('navigation','hamburger_menu','navigation',6),
  ('navigation','breadcrumbs','navigation',7),
  ('navigation','dock_menu','navigation',8),

  ('modals','glass_modal','modals',1),
  ('modals','dark_overlay','modals',2),
  ('modals','holographic_frame','modals',3),
  ('modals','float_card','modals',4),
  ('modals','neon_border','modals',5),
  ('modals','pattern_overlay','modals',6),
  ('modals','particle_backdrop','modals',7),
  ('modals','liquid_popup','modals',8),

  ('logo-treatments','logo_container','logo-treatments',1),
  ('logo-treatments','circular_badge','logo-treatments',2),
  ('logo-treatments','square_plate','logo-treatments',3),
  ('logo-treatments','neon_outline','logo-treatments',4),
  ('logo-treatments','embossed_3d','logo-treatments',5),
  ('logo-treatments','floating_logo','logo-treatments',6),
  ('logo-treatments','logo_reveal','logo-treatments',7),
  ('logo-treatments','watermark','logo-treatments',8),

  ('icon-badges','icon_badge','icon-badges',1),
  ('icon-badges','glass_icon_bg','icon-badges',2),
  ('icon-badges','metallic_badge','icon-badges',3),
  ('icon-badges','holographic_ring','icon-badges',4),
  ('icon-badges','burst_effect','icon-badges',5),
  ('icon-badges','hex_badge','icon-badges',6),
  ('icon-badges','platform_icon','icon-badges',7),
  ('icon-badges','orbital_frame','icon-badges',8),

  ('dividers','transparent_glow_barrier','dividers',1),
  ('dividers','floating_geometric_separator','dividers',2),
  ('dividers','dynamic_waveform_divider','dividers',3),
  ('dividers','particle_flow_transition','dividers',4),
  ('dividers','holographic_section_break','dividers',5),
  ('dividers','digital_transition_graphic','dividers',6),
  ('dividers','metallic_zigzag_separator','dividers',7),
  ('dividers','curved_metallic_divider','dividers',8),

  ('service-icons','web_development','service-icons',1),
  ('service-icons','mobile_apps','service-icons',2),
  ('service-icons','e_commerce','service-icons',3),
  ('service-icons','ui_ux_design','service-icons',4),
  ('service-icons','seo_marketing','service-icons',5),
  ('service-icons','consulting','service-icons',6),
  ('service-icons','service_card_bg','service-icons',7),
  ('service-icons','pricing_table_bg','service-icons',8),
  ('service-icons','email_marketing','service-icons',9),
  ('service-icons','seo','service-icons',10),
  ('service-icons','responsive_design','service-icons',11),
  ('service-icons','web_hosting','service-icons',12),
  ('service-icons','ssl_security','service-icons',13),
  ('service-icons','analytics','service-icons',14),

  ('blog-ui','featured_post_card_bg','blog-ui',1),
  ('blog-ui','blog_thumbnail_frame','blog-ui',2),
  ('blog-ui','category_badge_tech','blog-ui',3),
  ('blog-ui','category_badge_design','blog-ui',4),
  ('blog-ui','category_badge_business','blog-ui',5),
  ('blog-ui','author_avatar_frame','blog-ui',6),
  ('blog-ui','reading_time_icon','blog-ui',7),
  ('blog-ui','share_button_set','blog-ui',8),

  ('about-assets','team_member_card_3d','about-assets',1),
  ('about-assets','company_values_icon','about-assets',2),
  ('about-assets','mission_icon','about-assets',3),
  ('about-assets','vision_icon','about-assets',4),
  ('about-assets','achievement_badge','about-assets',5),
  ('about-assets','certification_badge','about-assets',6),
  ('about-assets','timeline_connector','about-assets',7),
  ('about-assets','about_hero_bg','about-assets',8),

  ('process-assets','animated_rotating_logo','process-assets',1),
  ('process-assets','floating_particle_overlay','process-assets',2),
  ('process-assets','discovery_phase','process-assets',3),
  ('process-assets','design_phase','process-assets',4),
  ('process-assets','development_phase','process-assets',5),
  ('process-assets','launch_phase','process-assets',6),
  ('process-assets','ai_academy','process-assets',7),

  ('loaders','flame_ring','loaders',1),
  ('loaders','vine_bar','loaders',2),
  ('loaders','wave_loader','loaders',3),
  ('loaders','orbit_loader','loaders',4),
  ('loaders','hourglass','loaders',5),
  ('loaders','snowflake','loaders',6),
  ('loaders','matrix_percent','loaders',7),
  ('loaders','dna_helix','loaders',8),
  ('loaders','morph_shapes','loaders',9),
  ('loaders','plasma_globe','loaders',10),
  ('loaders','skeleton_loader','loaders',11),
  ('loaders','holographic_connection','loaders',12)
ON CONFLICT (category, name) DO NOTHING;
