import type { Locale } from '@/i18n'

export type SeoPageKey =
  | 'home'
  | 'about'
  | 'process'
  | 'portfolio'
  | 'showcase'
  | 'services'
  | 'blog'
  | 'contact'

const BRAND = [
  'Protos',
  'Protos Web',
  'protosweb',
  'Protos Web Mark23',
  'protoswebmark23',
  'protoswebeu',
  'protoswebhr',
]

/** People, handles, nicknames — highest priority SEO identity signals. */
const PEOPLE = [
  'Dario Imsirović',
  'Dario Imsirovic',
  'Dario Imširović',
  'Imširović Dario',
  'Imsirovic Dario',
  'Imširović Dario',
  'ProtosEschatos',
  'protos_eschatos',
  'protos01eschatos',
  'imsirovicdario23',
  'dario.imsirovic',
  'imsirovicdarioprotosweb',
  'Martina Markulin',
  'everybodycries',
  '@everybodycries',
  'Martina Markulin Protos Web',
  'Dario Imsirović Martina Markulin',
  'Dario i Martina Protos Web',
]

const ROLE_TAGS = [
  'full stack developer',
  'full stack cross-web developer',
  'full stack 3D crossweb designer',
  'full stack 3D cross-web developer',
  'cross-web developer',
  'crossweb designer',
  '3D web designer',
  '3D web developer',
  'WebGL developer',
  'Three.js developer',
  'AI engineer',
  'AI inženjer',
  'shop UI designer',
  'shop UI dizajnerica',
  'frontend ekspert',
  'UI/UX dizajnerica',
]

/** Shared Balkan / ex-Yu geo tags (HR + Latin). */
const EX_YU = [
  'Hrvatska',
  'Zagreb',
  'Split',
  'Rijeka',
  'Osijek',
  'Županja',
  'Slovenija',
  'Ljubljana',
  'Srbija',
  'Beograd',
  'Novi Sad',
  'Bosna i Hercegovina',
  'BiH',
  'Sarajevo',
  'Banja Luka',
  'Mostar',
  'Crna Gora',
  'Podgorica',
  'Sjeverna Makedonija',
  'Skoplje',
  'Balkan',
  'balkanski web',
  'ex-Yu',
  'ex Yu',
  'bivša Jugoslavija',
  'Southeast Europe',
  'Jadran',
  'regija',
]

/** Portfolio / product names — keep in every locale for discovery. */
const PROJECTS = [
  'Bodulica Shop',
  'Bodulica',
  'Auto Moto Zagreb',
  'Golden Pawn',
  'LuminaDent',
  'System Boost',
  'Protos System Boost',
  'portfolio-showcase',
  '3D portfolio',
  'WebGL portfolio',
]

const KEYWORDS_BY_LOCALE: Record<Locale, string[]> = {
  hr: [
    ...PEOPLE,
    ...BRAND,
    ...ROLE_TAGS,
    ...PROJECTS,
    ...EX_YU,
    'izrada web stranica',
    'izrada web stranica po mjeri',
    'web dizajn',
    'web dizajn Zagreb',
    'web developer Zagreb',
    'web development Hrvatska',
    'UI dizajn',
    'UX dizajn',
    'UI/UX dizajn',
    'SEO optimizacija',
    'izrada web shopa',
    'e-trgovina',
    'web aplikacija',
    'održavanje web stranica',
    'Next.js developer',
    'React developer',
    'TypeScript',
    'Three.js',
    'WebGL',
    '3D web',
    'freelance web developer',
    'goLance',
    'Upwork',
    'Medium',
    'Blogger',
    'Tumblr',
    'About.me',
    'web studio Zagreb',
    'web studio Hrvatska',
    'digitalna agencija Zagreb',
    'izrada internet stranica',
    'moderna web rješenja',
    'responzivne web stranice',
    'brza web stranica',
    'web studio Balkan',
    'web developer ex-Yu',
  ],
  sr: [
    ...PEOPLE,
    ...BRAND,
    ...ROLE_TAGS,
    ...PROJECTS,
    ...EX_YU,
    'Дарио Имсировић',
    'Мартина Маркулин',
    'израда веб страница',
    'izrada sajta',
    'veb dizajn',
    'veb dizajn Beograd',
    'web developer',
    'UI dizajn',
    'UX dizajn',
    'SEO optimizacija',
    'izrada web shopa',
    'e-trgovina',
    'web aplikacija',
    'održavanje sajta',
    'Next.js developer',
    'React developer',
    'Three.js',
    'WebGL',
    '3D veb',
    'freelance web developer',
    'goLance',
    'Upwork',
    'web studio',
    'digitalna agencija',
    'balkanski sajtovi',
    'ex-Yu web',
  ],
  en: [
    ...PEOPLE,
    ...BRAND,
    ...ROLE_TAGS,
    ...PROJECTS,
    ...EX_YU,
    'Croatia',
    'Zagreb',
    'Slovenia',
    'Ljubljana',
    'Serbia',
    'Belgrade',
    'Bosnia and Herzegovina',
    'Sarajevo',
    'Montenegro',
    'Podgorica',
    'North Macedonia',
    'Skopje',
    'Balkans',
    'former Yugoslavia',
    'ex-Yugoslavia',
    'Southeast Europe',
    'web design',
    'website development',
    'custom website',
    'web developer Zagreb',
    'web design Croatia',
    'UI design',
    'UX design',
    'UI/UX design',
    'SEO optimization',
    'e-commerce development',
    'web application',
    'website maintenance',
    'Next.js developer',
    'React developer',
    'Three.js',
    'WebGL',
    '3D web experiences',
    'freelance web developer',
    'goLance',
    'Upwork',
    'web studio Zagreb',
    'digital agency Croatia',
    'Balkan web studio',
    'ex-Yu web developer',
    'modern web solutions',
    'responsive websites',
    'fast website',
    'EU web studio',
  ],
  de: [
    ...PEOPLE,
    ...BRAND,
    ...ROLE_TAGS,
    ...PROJECTS,
    ...EX_YU,
    'Kroatien',
    'Zagreb',
    'Slowenien',
    'Serbien',
    'Belgrad',
    'Bosnien und Herzegowina',
    'Montenegro',
    'Nordmazedonien',
    'Balkan',
    'ehemaliges Jugoslawien',
    'Ex-Yu',
    'Sudosteuropa',
    'Webdesign',
    'Website Entwicklung',
    'Webentwicklung',
    'Webdesign Zagreb',
    'Webentwickler Kroatien',
    'UI Design',
    'UX Design',
    'SEO Optimierung',
    'E-Commerce Entwicklung',
    'Webanwendung',
    'Website Wartung',
    'Next.js Entwickler',
    'React Entwickler',
    'Three.js',
    'WebGL',
    '3D Web',
    'Full Stack Entwickler',
    'KI Ingenieur',
    'Freelance Webentwickler',
    'goLance',
    'Upwork',
    'Webstudio Zagreb',
    'Digitale Agentur',
  ],
  it: [
    ...PEOPLE,
    ...BRAND,
    ...ROLE_TAGS,
    ...PROJECTS,
    ...EX_YU,
    'Croazia',
    'Zagabria',
    'Slovenia',
    'Serbia',
    'Belgrado',
    'Bosnia ed Erzegovina',
    'Montenegro',
    'Macedonia del Nord',
    'Balcani',
    'ex Jugoslavia',
    'ex-Yu',
    'Europa sud-orientale',
    'web design',
    'sviluppo siti web',
    'sito web su misura',
    'web designer Zagabria',
    'sviluppo web Croazia',
    'UI design',
    'UX design',
    'ottimizzazione SEO',
    'e-commerce',
    'applicazione web',
    'manutenzione siti',
    'sviluppatore Next.js',
    'sviluppatore React',
    'Three.js',
    'WebGL',
    'web 3D',
    'ingegnere AI',
    'freelance web developer',
    'goLance',
    'Upwork',
    'studio web Zagabria',
    'agenzia digitale',
  ],
  es: [
    ...PEOPLE,
    ...BRAND,
    ...ROLE_TAGS,
    ...PROJECTS,
    ...EX_YU,
    'Croacia',
    'Zagreb',
    'Eslovenia',
    'Serbia',
    'Belgrado',
    'Bosnia y Herzegovina',
    'Montenegro',
    'Macedonia del Norte',
    'Balcanes',
    'ex Yugoslavia',
    'ex-Yu',
    'Europa sudoriental',
    'diseno web',
    'desarrollo web',
    'pagina web a medida',
    'desarrollador web Zagreb',
    'diseno web Croacia',
    'diseno UI',
    'diseno UX',
    'optimizacion SEO',
    'e-commerce',
    'aplicacion web',
    'mantenimiento web',
    'desarrollador Next.js',
    'desarrollador React',
    'Three.js',
    'WebGL',
    'web 3D',
    'ingeniero IA',
    'freelance desarrollador web',
    'goLance',
    'Upwork',
    'estudio web Zagreb',
    'agencia digital',
  ],
}

const PAGE_KEYWORDS: Record<Locale, Record<SeoPageKey, string[]>> = {
  hr: {
    home: [
      'web stranice s dušom',
      'izrada web stranica cijena',
      'ponuda za web stranicu',
      'Protos Web Zagreb',
    ],
    about: [
      'Dario Imsirović',
      'Dario Imsirovic',
      'Dario Imširović',
      'Martina Markulin',
      'everybodycries',
      'ProtosEschatos',
      'protos_eschatos',
      'full stack 3D crossweb designer',
      'full stack cross-web developer',
      'AI inženjer Zagreb',
      'shop UI dizajnerica',
      'web tim Zagreb',
      'full stack duo',
      'Dario Imsirović Protos Web',
      'Martina Markulin dizajn',
      'goLance Dario',
      'ex-Yu web duo',
    ],
    process: ['proces izrade web stranice', 'konzultacije', 'lansiranje web stranice'],
    portfolio: [
      'web portfolio',
      'studija slučaja',
      'web projekti Balkan',
      'web projekti ex-Yu',
      'Bodulica Shop',
      'Auto Moto Zagreb',
      'Golden Pawn',
      'LuminaDent',
      'System Boost poklon',
      'Dario Imsirović portfolio',
      'Martina Markulin dizajn',
    ],
    showcase: [
      '3D web portfolio',
      'WebGL',
      'interaktivna galerija',
      'portfolio-showcase',
      'Bodulica',
      'LuminaDent',
      'Protos System Boost',
      'Dario Imsirović 3D',
      'crossweb 3D showcase',
    ],
    services: [
      'usluge web dizajna',
      'izrada web shopa',
      'SEO usluge',
      'održavanje stranica',
      'AI integracije',
      'Three.js 3D web',
      'full stack cross-web',
    ],
    blog: [
      'web akademija',
      'vodiči za poduzetnike',
      'SEO savjeti',
      'Dario Imsirovic blog',
      'Dario Imsirović Medium',
      'Protos Web Blogger',
      'Protos Web Tumblr',
    ],
    contact: [
      'besplatna konzultacija',
      'ponuda web stranice',
      'kontakt web studio',
      'WhatsApp Protos Web',
      'kontakt Dario Imsirović',
    ],
  },
  sr: {
    home: ['veb stranice', 'izrada sajta cena', 'ponuda za sajt', 'Protos Web Zagreb', 'ex-Yu'],
    about: [
      'Дарио Имсировић',
      'Мартина Маркулин',
      'Dario Imsirović',
      'Martina Markulin',
      'everybodycries',
      'full stack 3D crossweb',
      'veb tim Zagreb',
      'AI inženjer',
      'shop dizajner',
      'full stack duo',
      'ex-Yu',
    ],
    process: ['proces izrade sajta', 'konsultacije', 'lansiranje sajta'],
    portfolio: [
      'veb portfolio',
      'studija slučaja',
      'veb projekti Balkan',
      'Bodulica Shop',
      'Auto Moto Zagreb',
      'Golden Pawn',
      'LuminaDent',
    ],
    showcase: ['3D veb portfolio', 'WebGL', 'interaktivna galerija', 'System Boost', 'crossweb'],
    services: ['usluge veb dizajna', 'izrada web shopa', 'SEO usluge', 'održavanje sajtova', 'AI', '3D'],
    blog: ['veb akademija', 'vodiči za preduzetnike', 'SEO saveti', 'Medium', 'Blogger'],
    contact: ['besplatna konsultacija', 'ponuda za sajt', 'kontakt web studio', 'Dario Imsirović'],
  },
  en: {
    home: [
      'bespoke websites',
      'website quote',
      'hire web developer',
      'Protos Web Zagreb',
      'ex-Yu web studio',
    ],
    about: [
      'Dario Imsirović',
      'Dario Imsirovic',
      'Martina Markulin',
      'everybodycries',
      'ProtosEschatos',
      'full stack 3D crossweb designer',
      'full stack cross-web developer',
      'AI engineer Zagreb',
      'shop UI designer',
      'web team Zagreb',
      'full stack duo',
      'ex-Yu founders',
      'goLance Croatia',
    ],
    process: ['website process', 'consultation', 'website launch'],
    portfolio: [
      'web portfolio',
      'case studies',
      'Balkan web projects',
      'ex-Yu portfolio',
      'Bodulica Shop',
      'Auto Moto Zagreb',
      'Golden Pawn',
      'LuminaDent',
      'System Boost gift',
      'Dario Imsirovic portfolio',
    ],
    showcase: [
      '3D web portfolio',
      'WebGL',
      'interactive gallery',
      'portfolio-showcase',
      'Protos System Boost',
      'crossweb 3D',
    ],
    services: [
      'web design services',
      'e-commerce build',
      'SEO services',
      'website maintenance',
      'Three.js development',
      'full stack cross-web',
    ],
    blog: [
      'web guides',
      'entrepreneur tips',
      'SEO advice',
      'Protos Web blog',
      'Dario Imsirovic Medium',
      'Protos Web Blogger',
    ],
    contact: [
      'free consultation',
      'website quote',
      'contact web studio',
      'WhatsApp Zagreb',
      'contact Dario Imsirovic',
    ],
  },
  de: {
    home: ['Websites nach Maß', 'Website Angebot', 'Webentwickler beauftragen', 'Protos Web Zagreb'],
    about: ['Web Team Zagreb', 'KI Ingenieur', 'Shop UI Designerin', 'Full Stack Duo', 'Dario Imsirovic'],
    process: ['Website Prozess', 'Beratung', 'Website Launch'],
    portfolio: [
      'Web Portfolio',
      'Fallstudien',
      'Balkan Webprojekte',
      'Bodulica Shop',
      'Auto Moto Zagreb',
      'Golden Pawn',
      'LuminaDent',
    ],
    showcase: ['3D Web Portfolio', 'WebGL', 'interaktive Galerie', 'System Boost'],
    services: ['Webdesign Leistungen', 'E-Commerce', 'SEO Dienstleistungen', 'Wartung', 'Three.js'],
    blog: ['Web Ratgeber', 'Unternehmer Tipps', 'SEO Tipps'],
    contact: ['kostenlose Beratung', 'Website Angebot', 'Kontakt Webstudio'],
  },
  it: {
    home: ['siti su misura', 'preventivo sito web', 'assumere web developer', 'Protos Web Zagreb'],
    about: ['team web Zagabria', 'ingegnere AI', 'designer shop UI', 'duo full stack', 'Dario Imsirovic'],
    process: ['processo sito web', 'consulenza', 'lancio sito'],
    portfolio: [
      'portfolio web',
      'case study',
      'progetti web Balcani',
      'Bodulica Shop',
      'Auto Moto Zagreb',
      'Golden Pawn',
      'LuminaDent',
    ],
    showcase: ['portfolio 3D', 'WebGL', 'galleria interattiva', 'System Boost'],
    services: ['servizi web design', 'e-commerce', 'servizi SEO', 'manutenzione', 'Three.js'],
    blog: ['guide web', 'consigli imprenditori', 'consigli SEO'],
    contact: ['consulenza gratuita', 'preventivo sito', 'contatto studio web'],
  },
  es: {
    home: ['sitios a medida', 'presupuesto web', 'contratar desarrollador web', 'Protos Web Zagreb'],
    about: ['equipo web Zagreb', 'ingeniero IA', 'disenadora shop UI', 'duo full stack', 'Dario Imsirovic'],
    process: ['proceso web', 'consulta', 'lanzamiento web'],
    portfolio: [
      'portfolio web',
      'casos de estudio',
      'proyectos web Balcanes',
      'Bodulica Shop',
      'Auto Moto Zagreb',
      'Golden Pawn',
      'LuminaDent',
    ],
    showcase: ['portfolio 3D', 'WebGL', 'galeria interactiva', 'System Boost'],
    services: ['servicios diseno web', 'e-commerce', 'servicios SEO', 'mantenimiento', 'Three.js'],
    blog: ['guias web', 'consejos emprendedores', 'consejos SEO'],
    contact: ['consulta gratuita', 'presupuesto web', 'contacto estudio web'],
  },
}

function dedupeKeywords(items: string[]): string[] {
  const seen = new Set<string>()
  const out: string[] = []
  for (const item of items) {
    const key = item.trim().toLowerCase()
    if (!key || seen.has(key)) continue
    seen.add(key)
    out.push(item.trim())
  }
  return out
}

export function getGlobalKeywords(locale: string): string[] {
  const loc = (locale in KEYWORDS_BY_LOCALE ? locale : 'en') as Locale
  return KEYWORDS_BY_LOCALE[loc]
}

export function getPageKeywords(locale: string, page: SeoPageKey): string[] {
  const loc = (locale in PAGE_KEYWORDS ? locale : 'en') as Locale
  return PAGE_KEYWORDS[loc][page] ?? []
}

export function formatKeywords(locale: string, page?: SeoPageKey): string {
  const global = getGlobalKeywords(locale)
  const pageSpecific = page ? getPageKeywords(locale, page) : []
  return dedupeKeywords([...global, ...pageSpecific]).join(', ')
}

export function getServiceTypesForLocale(locale: string): string[] {
  const map: Record<Locale, string[]> = {
    hr: [
      'Izrada web stranica',
      'Web dizajn',
      'UI/UX dizajn',
      'SEO optimizacija',
      'E-trgovina',
      'Web aplikacije',
      '3D / WebGL iskustva',
      'Održavanje web stranica',
    ],
    sr: [
      'Izrada web stranica',
      'Veb dizajn',
      'UI/UX dizajn',
      'SEO optimizacija',
      'E-trgovina',
      'Web aplikacije',
      '3D / WebGL iskustva',
      'Održavanje sajtova',
    ],
    en: [
      'Website Development',
      'Web Design',
      'UI/UX Design',
      'SEO Optimization',
      'E-commerce',
      'Web Applications',
      '3D / WebGL Experiences',
      'Website Maintenance',
    ],
    de: [
      'Website Entwicklung',
      'Webdesign',
      'UI/UX Design',
      'SEO Optimierung',
      'E-Commerce',
      'Webanwendungen',
      '3D / WebGL Erlebnisse',
      'Website Wartung',
    ],
    it: [
      'Sviluppo siti web',
      'Web design',
      'UI/UX design',
      'Ottimizzazione SEO',
      'E-commerce',
      'Applicazioni web',
      'Esperienze 3D / WebGL',
      'Manutenzione siti',
    ],
    es: [
      'Desarrollo web',
      'Diseno web',
      'UI/UX design',
      'Optimizacion SEO',
      'E-commerce',
      'Aplicaciones web',
      'Experiencias 3D / WebGL',
      'Mantenimiento web',
    ],
  }
  const loc = (locale in map ? locale : 'en') as Locale
  return map[loc]
}
